name: d2pt win rate

on:
  schedule:
    - cron: '23 * * * *'
  workflow_dispatch:

jobs:
  fetch-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run fetch script
        run: python fetch_d2pt.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add d2pt_pos*.json
          git diff --staged --quiet || git commit -m "$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M')"
          git push
